---
deployment:
  tasks:
    - export DEPLOYPATH=/home/thenusex/renegades-book-review/
    - /bin/cp -R static $DEPLOYPATH
    - /bin/cp -R templates $DEPLOYPATH
    - /bin/cp application.py $DEPLOYPATH
